services:
  searchx_combolist_database:
    image: bitnami/postgresql:17
    container_name: searchx-combolist-pg
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: searchx_combolist
    ports:
      - "5433:5432"
    volumes:
      - ./data/postgresql:/bitnami/postgresql/data

  flyway_combolist:
    image: flyway/flyway:11.3
    container_name: flyway-combolist
    environment:
      FLYWAY_URL: jdbc:postgresql://searchx_combolist_database:5432/searchx_combolist
      FLYWAY_USER: docker
      FLYWAY_PASSWORD: docker
      FLYWAY_LOCATIONS: filesystem:/flyway/sql
    volumes:
      - ../../migrations/combolist:/flyway/sql
    command: ["migrate"]
    depends_on:
      - searchx_combolist_database